//* alphabets
export const alphabetGifs: Record<string, any> = {
  A: require("../../assets/letters/A/letterA.gif"),
  B: require("../../assets/letters/B/letterB.gif"),
  C: require("../../assets/letters/C/letterC.gif"),
  D: require("../../assets/letters/D/letterD.gif"),
  E: require("../../assets/letters/E/letterE.gif"),
  F: require("../../assets/letters/F/letterF.gif"),
  G: require("../../assets/letters/G/letterG.gif"),
  H: require("../../assets/letters/H/letterH.gif"),
  I: require("../../assets/letters/I/letterI.gif"),
  J: require("../../assets/letters/J/letterJ.gif"),
  K: require("../../assets/letters/K/letterK.gif"),
  L: require("../../assets/letters/L/letterL.gif"),
  M: require("../../assets/letters/M/letterM.gif"),
  N: require("../../assets/letters/N/letterN.gif"),
  O: require("../../assets/letters/O/letterO.gif"),
  P: require("../../assets/letters/P/letterP.gif"),
  Q: require("../../assets/letters/Q/letterQ.gif"),
  R: require("../../assets/letters/R/letterR.gif"),
  S: require("../../assets/letters/S/letterS.gif"),
  T: require("../../assets/letters/T/letterT.gif"),
  U: require("../../assets/letters/U/letterU.gif"),
  V: require("../../assets/letters/V/letterV.gif"),
  W: require("../../assets/letters/W/letterW.gif"),
  X: require("../../assets/letters/X/letterX.gif"),
  Y: require("../../assets/letters/Y/letterY.gif"),
  Z: require("../../assets/letters/Z/letterZ.gif"),
};

export const alphabetSounds: Record<string, any> = {
  A: require("../../assets/alphabetSounds/a.mp3"),
  B: require("../../assets/alphabetSounds/b.mp3"),
  C: require("../../assets/alphabetSounds/c.mp3"),
  D: require("../../assets/alphabetSounds/d.mp3"),
  E: require("../../assets/alphabetSounds/e.mp3"),
  F: require("../../assets/alphabetSounds/f.mp3"),
  G: require("../../assets/alphabetSounds/g.mp3"),
  H: require("../../assets/alphabetSounds/h.mp3"),
  I: require("../../assets/alphabetSounds/i.mp3"),
  J: require("../../assets/alphabetSounds/j.mp3"),
  K: require("../../assets/alphabetSounds/k.mp3"),
  L: require("../../assets/alphabetSounds/l.mp3"),
  M: require("../../assets/alphabetSounds/m.mp3"),
  N: require("../../assets/alphabetSounds/n.mp3"),
  O: require("../../assets/alphabetSounds/o.mp3"),
  P: require("../../assets/alphabetSounds/p.mp3"),
  Q: require("../../assets/alphabetSounds/q.mp3"),
  R: require("../../assets/alphabetSounds/r.mp3"),
  S: require("../../assets/alphabetSounds/s.mp3"),
  T: require("../../assets/alphabetSounds/t.mp3"),
  U: require("../../assets/alphabetSounds/u.mp3"),
  V: require("../../assets/alphabetSounds/v.mp3"),
  W: require("../../assets/alphabetSounds/w.mp3"),
  X: require("../../assets/alphabetSounds/x.mp3"),
  Y: require("../../assets/alphabetSounds/y.mp3"),
  Z: require("../../assets/alphabetSounds/z.mp3"),
};

//* shapes
export const shapesGifs: Record<string, any> = {
  circle: require("../../assets/shapes/circle.gif"),
  oval: require("../../assets/shapes/oval.gif"),
  rectangle: require("../../assets/shapes/rectangle.gif"),
  square: require("../../assets/shapes/square.gif"),
  triangle: require("../../assets/shapes/triangle.gif"),
};

export const shapesSounds: Record<string, any> = {
  circle: require("../../assets/shapeSounds/circle.mp3"),
  oval: require("../../assets/shapeSounds/oval.mp3"),
  rectangle: require("../../assets/shapeSounds/rectangle.mp3"),
  square: require("../../assets/shapeSounds/square.mp3"),
  triangle: require("../../assets/shapeSounds/triangle.mp3"),
};
